name: fmp
description: A Flutter CLI tool to generate MVVM project structure using Provider.
executables:
  fmp: fmp
version: 1.0.1
repository: https://github.com/mdnahidhossen1911/FMP
homepage: https://github.com/mdnahidhossen1911/FMP
issue_tracker: https://github.com/mdnahidhossen1911/FMP/issues
publisher: nahid.info.bd

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0



